#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Please specify package name"
    exit 1
fi

PKGNAME=$1
OUTPUT=/tmp/awesomepkg
AUTHOR="Awesome Person <root@localhost>"

rm -rf $OUTPUT
mkdir -p $OUTPUT/DEBIAN
make install INSTALL_ROOT=$OUTPUT

echo "Package: $PKGNAME
Version: 999:999
Architecture: $DEB_HOST_ARCH
Maintainer: $AUTHOR
Description: fake package developed by a lazy developer." > $OUTPUT/DEBIAN/control

dpkg-deb -b $OUTPUT $PKGNAME.deb
