#!/bin/bash

PKGNAME=$1
OUTPUT=/tmp/awesomepkg/$PKGNAME
AUTHOR="Awesome Person <root@localhost>"

rm -rf $OUTPUT
mkdir -p $OUTPUT/DEBIAN
make install/fast DESTDIR=$OUTPUT

echo "Package: $PKGNAME
Version: 999:999
Architecture: all
Maintainer: $AUTHOR
Description: fake override package for kubuntu ci install checks" > $OUTPUT/DEBIAN/control

dpkg-deb -b $OUTPUT $PKGNAME.deb

