#!/bin/bash

PKGNAME=$1
OUTPUT=/tmp/awesomepkg
AUTHOR="Awesome Person <root@localhost>"

make install INSTALL_ROOT=$OUTPUT

mkdir -p $OUTPUT/DEBIAN
echo "Package: $PKGNAME
Version: 999:999
Architecture: all
Maintainer: $AUTHOR
Description: fake override package for kubuntu ci install checks" > $OUTPUT/DEBIAN/control

dpkg-deb -b $OUTPUT $PKGNAME.deb

