#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Please specify package name"
    exit 1
elif [ -z $DEB_HOST_ARCH ]; then
    echo "Should have DEB_HOST_ARCH defined"
    exit 2
fi

PKGNAME=$1
OUTPUT=/tmp/awesomepkg/$PKGNAME
AUTHOR="Awesome Person <root@localhost>"

rm -rf $OUTPUT
mkdir -p $OUTPUT/DEBIAN
make install/fast DESTDIR=$OUTPUT

echo "Package: $PKGNAME
Version: 999:999
Architecture: $DEB_HOST_ARCH
Maintainer: $AUTHOR
Description: fake package developed by a lazy developer." > $OUTPUT/DEBIAN/control

dpkg-deb -b $OUTPUT $PKGNAME.deb

